version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "80:80"
      
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/webackbd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=weback123

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: webackbd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: weback123
    ports:
      - "5432:5432"
